
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AND APPEND AROUND ASSIGN CHARACTER CIRCLE COLON COMMA DIGIT DOT DRAW END GRID ID LBRACKET LINE LPAREN OPERATOR QUOTE RBRACKET REGARDING ROTATE RPAREN SEMIC SIN START TOexpresion : START ID ASSIGN Operation COLON Function LPAREN ParameterList RPAREN Location SEMIC END\n                 | APPEND ID TO ID SEMIC\n                 | ROTATE ID AROUND ID SEMIC\n                 | START END\n                 | ENDParameterList : Parameter AND ParameterList \n                     | Parameter \n                     | emptyParameter : ID ASSIGN DIGIT \n                 | ID ASSIGN String\n                 | LINE ASSIGN String String : QUOTE ID QUOTEOperation : DRAWFunction : SIN \n                | CIRCLE \n                | GRID \n                | LINELocation : REGARDING Coordinate\n                | emptyCoordinate : ID \n                  | LPAREN DIGIT COMMA DIGIT RPARENempty :'
    
_lr_action_items = {'START':([0,],[2,]),'APPEND':([0,],[4,]),'ROTATE':([0,],[5,]),'END':([0,2,44,],[3,7,49,]),'$end':([1,3,7,18,19,49,],[0,-5,-4,-2,-3,-1,]),'ID':([2,4,5,11,12,25,33,37,39,],[6,8,9,15,16,26,26,43,46,]),'ASSIGN':([6,26,30,],[10,31,34,]),'TO':([8,],[11,]),'AROUND':([9,],[12,]),'DRAW':([10,],[14,]),'COLON':([13,14,],[17,-13,]),'SEMIC':([15,16,32,38,40,45,46,53,],[18,19,-22,44,-19,-18,-20,-21,]),'SIN':([17,],[21,]),'CIRCLE':([17,],[22,]),'GRID':([17,],[23,]),'LINE':([17,25,33,],[24,30,30,]),'LPAREN':([20,21,22,23,24,39,],[25,-14,-15,-16,-17,47,]),'RPAREN':([25,27,28,29,33,35,36,41,42,48,52,],[-22,32,-7,-8,-22,-9,-10,-6,-11,-12,53,]),'AND':([28,35,36,42,48,],[33,-9,-10,-11,-12,]),'DIGIT':([31,47,51,],[35,50,52,]),'QUOTE':([31,34,43,],[37,37,48,]),'REGARDING':([32,],[39,]),'COMMA':([50,],[51,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expresion':([0,],[1,]),'Operation':([10,],[13,]),'Function':([17,],[20,]),'ParameterList':([25,33,],[27,41,]),'Parameter':([25,33,],[28,28,]),'empty':([25,32,33,],[29,40,29,]),'String':([31,34,],[36,42,]),'Location':([32,],[38,]),'Coordinate':([39,],[45,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expresion","S'",1,None,None,None),
  ('expresion -> START ID ASSIGN Operation COLON Function LPAREN ParameterList RPAREN Location SEMIC END','expresion',12,'p_expression_ID','parser.py',14),
  ('expresion -> APPEND ID TO ID SEMIC','expresion',5,'p_expression_ID','parser.py',15),
  ('expresion -> ROTATE ID AROUND ID SEMIC','expresion',5,'p_expression_ID','parser.py',16),
  ('expresion -> START END','expresion',2,'p_expression_ID','parser.py',17),
  ('expresion -> END','expresion',1,'p_expression_ID','parser.py',18),
  ('ParameterList -> Parameter AND ParameterList','ParameterList',3,'p_param_list','parser.py',43),
  ('ParameterList -> Parameter','ParameterList',1,'p_param_list','parser.py',44),
  ('ParameterList -> empty','ParameterList',1,'p_param_list','parser.py',45),
  ('Parameter -> ID ASSIGN DIGIT','Parameter',3,'p_parameter','parser.py',50),
  ('Parameter -> ID ASSIGN String','Parameter',3,'p_parameter','parser.py',51),
  ('Parameter -> LINE ASSIGN String','Parameter',3,'p_parameter','parser.py',52),
  ('String -> QUOTE ID QUOTE','String',3,'p_string','parser.py',58),
  ('Operation -> DRAW','Operation',1,'p_operation','parser.py',62),
  ('Function -> SIN','Function',1,'p_function','parser.py',66),
  ('Function -> CIRCLE','Function',1,'p_function','parser.py',67),
  ('Function -> GRID','Function',1,'p_function','parser.py',68),
  ('Function -> LINE','Function',1,'p_function','parser.py',69),
  ('Location -> REGARDING Coordinate','Location',2,'p_location','parser.py',74),
  ('Location -> empty','Location',1,'p_location','parser.py',75),
  ('Coordinate -> ID','Coordinate',1,'p_coordinate','parser.py',80),
  ('Coordinate -> LPAREN DIGIT COMMA DIGIT RPAREN','Coordinate',5,'p_coordinate','parser.py',81),
  ('empty -> <empty>','empty',0,'p_empty','parser.py',87),
]
